LABELS = ["AR Dépôt",
"Certificat officiel",
"Confirmation d’abandon",
"Confirmation de maintien",
"Confirmation de paiement taxes",
"Confirmation de prolongation de délai",
"Confirmation de réponse à notification",
"Contrat",
"Courrier officiel",
"Délivrance",
"Demande client (devis)",
"Demande de pouvoirs",
"Désignation d’inventeurs",
"Devis",
"Document petite entité",
"Echange client",
"Echange correspondant",
"Email de confirmation",
"Facture",
"Fiche de dépôt",
"Formulaire administratif",
"Instructions client (délivrance",
"Instructions client (examen)",
"Instructions client (ext)",
"Instructions client (pasnat)",
"Instructions client (réponse notif)",
"Instructions client (valid)",
"Intention de délivrance",
"Notification (délivrance)",
"Notification (examen)",
"Pouvoirs signés clients",
"Preuves d’usage",
"Publication",
"Rappel",
"Rapport de dépôt",
"Rapport de recherche (transmission)",
"Rejet",
"Remboursement taxes",
"Réponse à notification",
"Traductions",
"Validation"   
]




#     "Taxes / Annuités",
#     "Délais / Urgences",
#     "Réponse à notification",
#     "Extension territoriale (EP / PCT)",
#     "Transmission d'informations client",
#     "Formalités administratives",
#     "Vérification devis / frais",
#     "Informations générales",
#     "Dossier marque (INPI / EUIPO / WIPO)",
#     "Demande de rendez-vous",
#     "Demande de devis ou paiement",
#     "Demande d’assistance ou clarification",
#     "Envoi de document",
#     "Contrats / Cessions / Licences"
# ]